// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: stockapi/stockapi.proto

package stockapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.3g2.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockPerdictionClient is the client API for StockPerdiction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockPerdictionClient interface {
	GetStock(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*APIReturn, error)
}

type stockPerdictionClient struct {
	cc grpc.ClientConnInterface
}

func NewStockPerdictionClient(cc grpc.ClientConnInterface) StockPerdictionClient {
	return &stockPerdictionClient{cc}
}

func (c *stockPerdictionClient) GetStock(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*APIReturn, error) {
	out := new(APIReturn)
	err := c.cc.Invoke(ctx, "/stockapi.StockPerdiction/getStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockPerdictionServer is the server API for StockPerdiction service.
// All implementations must embed UnimplementedStockPerdictionServer
// for forward compatibility
type StockPerdictionServer interface {
	GetStock(context.Context, *APIRequest) (*APIReturn, error)
	mustEmbedUnimplementedStockPerdictionServer()
}

// UnimplementedStockPerdictionServer must be embedded to have forward compatible implementations.
type UnimplementedStockPerdictionServer struct {
}

func (UnimplementedStockPerdictionServer) GetStock(context.Context, *APIRequest) (*APIReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedStockPerdictionServer) mustEmbedUnimplementedStockPerdictionServer() {}

// UnsafeStockPerdictionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockPerdictionServer will
// result in compilation errors.
type UnsafeStockPerdictionServer interface {
	mustEmbedUnimplementedStockPerdictionServer()
}

func RegisterStockPerdictionServer(s grpc.ServiceRegistrar, srv StockPerdictionServer) {
	s.RegisterService(&StockPerdiction_ServiceDesc, srv)
}

func _StockPerdiction_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockPerdictionServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stockapi.StockPerdiction/getStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockPerdictionServer).GetStock(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockPerdiction_ServiceDesc is the grpc.ServiceDesc for StockPerdiction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockPerdiction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockapi.StockPerdiction",
	HandlerType: (*StockPerdictionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStock",
			Handler:    _StockPerdiction_GetStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stockapi/stockapi.proto",
}
